package com.swingspringer.practice.Playground.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "Playground-dynamodb")
@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Transaction {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String transactionId;
    @DynamoDBAutoGeneratedKey
    private String hashKey;
    @DynamoDBAutoGeneratedKey
    private String test;
}
